<a href="https://colab.research.google.com/github/fatimahhasan7579-hub/Numpy-task/blob/main/Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Name: bibi fatima
#Rollno: 893229

In [ ]:
# Student Practice Tasks

## Task 1
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Average:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

Sum: 150
Average: 30.0
Maximum: 50
Minimum: 10


In [ ]:
#Task 2
import numpy as np

marks = np.array([40, 90, 50, 60])

print(marks+5)

[45 95 55 65]


In [ ]:
#Task 3

import numpy as np

numbers = np.array([1, 2, 3, 4, 5, 6])
new_array = numbers.reshape(2, 3)
print(new_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Task 4
import numpy as np

marks = np.random.randint(40, 100, 10)

print("Marks:", marks)
print("Average:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))

Marks: [99 52 53 85 92 58 94 98 81 69]
Average: 78.1
Highest Marks: 99
Lowest Marks: 52


In [ ]:
#Task 5
import numpy as np
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed = marks[marks >= 50]
failed = marks[marks < 50]

print("Passed Marks:", passed)
print("Failed Marks:", failed)

print("Number of Passed Students:", len(passed))
print("Number of Failed Students:", len(failed))


Passed Marks: [67 89 90 70 58]
Failed Marks: [35 45 22]
Number of Passed Students: 5
Number of Failed Students: 3


1. Import NumPy

In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print(np.mean(numbers))
print(np.max(numbers))

[10 20 30 40 50]
30.0
50


2. Python List vs NumPy Array

In [ ]:
import numpy as np

marks = np.array([40, 90, 50, 60])

print(marks+5)

[45 95 55 65]


3. Creating NumPy Arrays

Two-Dimention Array




In [ ]:
marks = np.array([
    [50,10,20,80,70],
    [40,50,10,50,60]
    ])
print(marks)

[[50 10 20 80 70]
 [40 50 10 50 60]]


4. Important Array Properties

In [ ]:
marks = np.array([
    [90,40,50,70,40],
    [60,60,90,40,40],
    [70,80,20,30,50]
    ])
print(marks.ndim)
print(marks.shape)
print(marks.size)
print(marks.dtype)

2
(3, 5)
15
int64


5. Indexing

In [ ]:
marks = np.array([50,70,90,20,60])
print(marks[0])
print(marks[-4])

50
70


6. Indexing in a 2D Array

In [ ]:
marks = np.array([
    [50,70,40,60,20],
    [30,20,70,80,50]
    ])
print(marks[0, 2])
print(marks[1, -2])

40
80


7. Slicing

In [ ]:
marks = np.array([40,60,20,30,50])
print(marks[1:4])

marks = np.array([
    [40,60,20,30,50],
    [30,20,80,70,90]
    ])
print(marks[1,1:4])

[60 20 30]
[20 80 70]


8. Vectorized Operations

In [ ]:
marks = np.array([70,40,50,90,80])
print(marks + 5)
print(marks - 5)
print(marks * 5)
print(marks / 5)

[75 45 55 95 85]
[65 35 45 85 75]
[350 200 250 450 400]
[14.  8. 10. 18. 16.]


9. Operations Between Two Arrays

In [ ]:
std1_marks = np.array([60,30,50,70,80])
std2_marks = np.array([40,20,70,30,90])

print(std1_marks + std2_marks)
print(std1_marks - std2_marks)
print(std1_marks * std2_marks)
print(std1_marks / std2_marks)

[100  50 120 100 170]
[ 20  10 -20  40 -10]
[2400  600 3500 2100 7200]
[1.5        1.5        0.71428571 2.33333333 0.88888889]


10. Mathematical Functions

In [ ]:
std1_marks = np.array([70,60,30,80,10])
print(np.sqrt(std1_marks))
print(np.power(std1_marks , 2))
std2_marks = np.array([40,-90,20,-70,30])
print(np.abs(std2_marks))
std3_marks = np.array([40.9,50.6,39.0,70.5,90.8])
print(np.round(std3_marks))

[8.36660027 7.74596669 5.47722558 8.94427191 3.16227766]
[4900 3600  900 6400  100]
[40 90 20 70 30]
[41. 51. 39. 70. 91.]


11. Aggregation Functions

In [ ]:
import numpy as np

marks = np.array([70, 85, 60, 95, 80])

print("Marks:", marks)

print("Sum:", np.sum(marks))
print("Average:", np.mean(marks))
print("Maximum Value:", np.max(marks))
print("Minimum Value:", np.min(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))

Marks: [70 85 60 95 80]
Sum: 390
Average: 78.0
Maximum Value: 95
Minimum Value: 60
Median: 80.0
Standard Deviation: 12.083045973594572


12. Conditions in NumPy

In [ ]:
import numpy as np

marks = np.array([30, 50, 80, 45, 90, 20])

print("Marks:", marks)

print("Marks >= 50:")
print(marks >= 50)

print("Marks > 50:")
print(marks > 50)

print("Marks < 50:")
print(marks < 50)

print("Marks == 50:")
print(marks == 50)

Marks: [30 50 80 45 90 20]
Marks >= 50:
[False  True  True False  True False]
Marks > 50:
[False False  True False  True False]
Marks < 50:
[ True False False  True False  True]
Marks == 50:
[False  True False False False False]


13. Filtering Data

In [ ]:
import numpy as np

marks = np.array([20, 40, 50, 45, 80, 70])

passed = marks[marks >= 50]
print(passed)

failed = marks[marks < 50]
print(failed)

[50 80 70]
[20 40 45]


14. Reshape

In [ ]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5, 6])
new_array = numbers.reshape(2, 3)

print(new_array)

[[1 2 3]
 [4 5 6]]


15. Flatten

In [ ]:
import numpy as np

data = np.array([ [1, 2, 3], [4, 5, 6] ])

print(data.flatten())

[1 2 3 4 5 6]


16. Useful NumPy Functions

In [ ]:
import numpy as np

print(np.zeros(5))
print(np.ones(5))
print(np.arange(1, 11))
print(np.arange(0, 11, 2))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


17. Random Numbers

In [ ]:
import numpy as np

marks = np.random.randint(40, 100, 10)
print(marks)

[46 98 72 58 97 89 76 69 95 40]
